employeeName=input("Enter employee name : \n")
employeeAge=int(input("Enter employee age : \t"))
employeeSalary=input("Enter employee salary : \n")
print(employeeSalary)
employeeSalary=float(employeeSalary)
print("employee name is\n",employeeName,type(employeeName))
print("employee age is",employeeAge,type(employeeAge))
print("employee salary is \t",employeeSalary,type(employeeSalary))
